import { Router } from 'express';
import { protectAdmin } from '../middleware/auth.js';
import { uploadImage } from '../middleware/upload.js';
import { getDashboard } from '../controllers/dashboardController.js';
import { listBookings, resendConfirmation, setBookingStatus } from '../controllers/bookingController.js';
import { getCabins, updateAvailability, updateCabin } from '../controllers/cabinController.js';
import { createCategory, createItem, deleteCategory, deleteItem, getAdminMenu, updateCategory, updateItem } from '../controllers/menuController.js';
import { deleteGalleryImage, getAdminGallery, updateGalleryImage, uploadGalleryImage } from '../controllers/galleryController.js';

const router = Router();
router.use(protectAdmin);
router.get('/dashboard', getDashboard);
router.get('/bookings', listBookings);
router.patch('/bookings/:id/status', setBookingStatus);
router.post('/bookings/:id/resend-confirmation', resendConfirmation);
router.get('/cabins', getCabins);
router.patch('/cabins/:id/availability', updateAvailability);
router.patch('/cabins/:id', updateCabin);
router.get('/menu', getAdminMenu);
router.post('/menu/categories', createCategory);
router.patch('/menu/categories/:categoryId', updateCategory);
router.delete('/menu/categories/:categoryId', deleteCategory);
router.post('/menu/categories/:categoryId/items', createItem);
router.patch('/menu/categories/:categoryId/items/:itemId', updateItem);
router.delete('/menu/categories/:categoryId/items/:itemId', deleteItem);
router.get('/gallery', getAdminGallery);
router.post('/gallery', uploadImage.single('image'), uploadGalleryImage);
router.patch('/gallery/:id', updateGalleryImage);
router.delete('/gallery/:id', deleteGalleryImage);
export default router;
